// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: port_Led

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_background_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TempLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel1, -39);
    lv_obj_set_y(ui_TempLabel1, -66);
    lv_obj_set_align(ui_TempLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel1, "25");
    lv_obj_set_style_text_color(ui_TempLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiLabel2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumiLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiLabel2, -40);
    lv_obj_set_y(ui_HumiLabel2, 41);
    lv_obj_set_align(ui_HumiLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumiLabel2, "60");
    lv_obj_set_style_text_color(ui_HumiLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumiLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumiLabel2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
