// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: 4_3Port

#ifndef _4_3PORT_UI_H
#define _4_3PORT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_TempLabel1;
extern lv_obj_t * ui_HumiLabel2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
